<#
.Synopsis
   Cmdlet used to get Idrac attribute using REDFISH API.

.DESCRIPTION
   Cmdlet used to get Idrac attribute using REDFISH API.

.PARAMETER Ip_Idrac

    Specifies the IpAddress of Remote system's Idrac.

.PARAMETER Credential

    Specifies the credentials for Idrac connection.

.PARAMETER Session

    Specifies the session generated by New-RacSession for Idrac connection.

.PARAMETER Attribute

    Specifies the attribute that has to be read.

.PARAMETER Value

    Specifies the value for the attribute.

.EXAMPLE
    Get-RacManagerDellAttribute -Ip_Idrac 10.2.160.84 -Credential $Cred -Attribute 'ServerPwr.1.RapidOnPrimaryPSU'

    This example grabs the value of the attrubute ServerPwr.1.RapidOnPrimaryPSU

.LINK


#>


Function Get-RacManagerDellAttribute {
    [CmdletBinding(DefaultParameterSetName = 'Host')]
    param(
        [Parameter(ParameterSetName = "Creds")]
        [Parameter(Mandatory = $true, ParameterSetName = 'Ip')]
        [Alias("idrac_ip")]
        [IpAddress]$Ip_Idrac,
        [Parameter(ParameterSetName = "Creds")]
        [Parameter(Mandatory = $true, ParameterSetName = 'Host')]
        [Alias("Server")]
        [string]$Hostname,
        [Parameter(Mandatory = $true, ParameterSetName = "Creds")]
        [pscredential]$Credential,
        [Parameter(Mandatory = $true, ParameterSetName = "Session")]
        [PSCustomObject]$Session,
        [Parameter(Mandatory = $false)]
        [string]$Attribute,
        [string]$Value,

        [Switch]$NoProxy
    )

    Switch ($PsCmdlet.ParameterSetName) {
        Creds {
            $WebRequestParameter = @{
                Headers     = @{"Accept" = "application/json" }
                Credential  = $Credential
                Method      = 'Get'
                ContentType = 'application/json'
            }
        }

        Session {
            $WebRequestParameter = @{
                Headers = $Session.Headers
                Method  = 'Get'
            }
            $Ip_Idrac = $Session.IPAddress
        }
    }

    If (! $NoProxy) { Set-myProxyAsDefault -Uri "Https://$Ip_Idrac" | Out-null }
    Else {
        Write-Verbose "No proxy requested"
        $Proxy = [System.Net.WebProxy]::new()
        $WebSession = [Microsoft.PowerShell.Commands.WebRequestSession]::new()
        $WebSession.Proxy = $Proxy
        $WebRequestParameter.WebSession = $WebSession
        If ($PSVersionTable.PSVersion.Major -gt 5) { $WebRequestParameter.SkipCertificateCheck = $true }
    }

    # Change Password for User specified
    $JsonBody = @{
        "Attributes" = @{
            $Attribute = $Value
        }
    } | ConvertTo-Json -Compress

    $GetUri = "https://$Ip_Idrac/redfish/v1/Managers/iDRAC.Embedded.1/Oem/Dell/DellAttributes/System.Embedded.1"
    If ($PSBoundParameters.ContainsKey('Attribute')) { $GetUri += "?`$select=Attributes/$Attribute" }

    $WebRequestParameter.Uri = $GetUri

    Try {
        $GetResult = Invoke-RestMethod @WebRequestParameter
    } Catch {
        Throw $_
    }

    $Object = $GetResult.Attributes

    If ($null -eq $Object) {
        Write-host "This attribute does not exist"
    } Else {
        Return  $Object
    }
}

Export-ModuleMember Get-RacManagerDellAttribute