<#
.Synopsis
   Cmdlet used to reset Idrac using REDFISH API.

.DESCRIPTION
   Cmdlet used to reset Idrac using REDFISH API.

.PARAMETER Ip_Idrac

    Specifies the IpAddress of Remote system's Idrac.

.PARAMETER Credential

    Specifies the credentials for Idrac connection.

.PARAMETER Session

    Specifies the session generated by New-RacSession for Idrac connection.

.EXAMPLE
    Reset-RacIdrac -Ip_Idrac 10.2.160.84 -Credential $Cred

    This example reset Idrac behind 10.2.160.84

.LINK
#>

Function Reset-RacIdrac {
    [CmdletBinding()]
	param(
		[Parameter(Mandatory=$true, ParameterSetName = "Creds")]
        [string]$Ip_Idrac,
        [Parameter(Mandatory=$true, ParameterSetName = "Creds")]
        [pscredential]$Credential,
        [Parameter(Mandatory=$true, ParameterSetName = "Session")]
        [PSCustomObject]$Session
	)

        Switch ($PsCmdlet.ParameterSetName) {
            Creds {
                $WebRequestParameter = @{
                    Headers = @{"Accept"="application/json"}
                    Credential = $Credential
                    Method = 'Post'
                    ContentType = 'application/json'
                }
            }

            Session {
                $WebRequestParameter = @{
                    Headers = $Session.Headers
                    Method = 'Post'
                }
                $Ip_Idrac = $Session.IPAddress
            }
        }

    $JsonBody = @{"ResetType"="GracefulRestart"}
    $JsonBody = $JsonBody | ConvertTo-Json -Compress

    $PostUri = "https://$Ip_Idrac/redfish/v1/Managers/iDRAC.Embedded.1/Actions/Manager.Reset"
    $WebRequestParameter.Uri = $PostUri
    Try {
        $PostResult = Invoke-RestMethod @WebRequestParameter
        if ($PostResult.StatusCode -eq 200 -or $PostResult.StatusCode -eq 202) {
             Write-Host "Idrac is about to be reset."
        }  else {
            $status_code = $result.StatusCode
            Write-Host "Reset request has failed with code $status_code."
            return
       }
    } Catch {
        Throw $_
    }

}
Export-ModuleMember Reset-RacIdrac
