<#
.Synopsis
   Cmdlet used to reset Idrac using REDFISH API.

.DESCRIPTION
   Cmdlet used to reset Idrac using REDFISH API.

.PARAMETER Ip_Idrac

    Specifies the IpAddress of Remote system's Idrac.

.PARAMETER Credential

    Specifies the credentials for Idrac connection.

.PARAMETER Session

    Specifies the session generated by New-RacSession for Idrac connection.

.EXAMPLE
    Reset-RacIdrac -Ip_Idrac 10.2.160.84 -Credential $Cred

    This example reset Idrac behind 10.2.160.84

.LINK
#>

Function Reset-RacIdrac {
    [CmdletBinding(DefaultParameterSetName='Host')]
	param(
		[Parameter(ParameterSetName = "Creds")]
        [Parameter(Mandatory=$true, ParameterSetName='Ip')]
        [Alias("idrac_ip")]
        [IpAddress]$Ip_Idrac,
		[Parameter(ParameterSetName = "Creds")]
        [Parameter(Mandatory=$true, ParameterSetName='Host')]
        [Alias("Server")]
        [string]$Hostname,
        [Parameter(Mandatory=$true, ParameterSetName = "Creds")]
        [pscredential]$Credential,
        [Parameter(Mandatory=$true, ParameterSetName = "Session")]
        [PSCustomObject]$Session, 
        [Switch]$NoProxy
	)

    If ($PSBoundParameters['Hostname']) {
        $Ip_Idrac = [system.net.dns]::Resolve($Hostname).AddressList.IPAddressToString
    }

    Switch ($PsCmdlet.ParameterSetName) {
        Creds {
            $WebRequestParameter = @{
                Headers = @{"Accept"="application/json"}
                Credential = $Credential
                Method = 'Post'
                ContentType = 'application/json'
            }
        }

        Session {
            $WebRequestParameter = @{
                Headers = $Session.Headers
                Method = 'Post'
            }
            $Ip_Idrac = $Session.IPAddress
        }
    }

    If (! $NoProxy) { Set-myProxyAsDefault -Uri "Https://$Ip_Idrac" | Out-null }
    Else {
        Write-Verbose "No proxy requested"
        $Proxy = [System.Net.WebProxy]::new()
        $WebSession = [Microsoft.PowerShell.Commands.WebRequestSession]::new()
        $WebSession.Proxy = $Proxy
        $WebRequestParameter.WebSession = $WebSession
        If ($PSVersionTable.PSVersion.Major -gt 5) { $WebRequestParameter.SkipCertificateCheck = $true }
    }

    $JsonBody = @{"ResetType"="GracefulRestart"}
    $JsonBody = $JsonBody | ConvertTo-Json -Compress
    $WebRequestParameter.Body = $JsonBody

    $PostUri = "https://$Ip_Idrac/redfish/v1/Managers/iDRAC.Embedded.1/Actions/Manager.Reset"
    $WebRequestParameter.Uri = $PostUri


    Try {
        
        $PostResult = Invoke-WebRequest @WebRequestParameter
        If ($PostResult.StatusCode -eq 200 -or $PostResult.StatusCode -eq 202) {
             Write-Host "Idrac is about to be reset."
        } Else {
            $status_code = $PostResult.StatusCode
            Write-Host "Reset request has failed with code $status_code."
            Return
       }
    } Catch {
        Throw $_
    }

}
Export-ModuleMember Reset-RacIdrac
