<#

.DESCRIPTION

Ce script permet de configurer les cartes idrac9 intégrées sur les serveurs DELL

.PARAMETER Ip_Idrac

    Specifies the IpAddress of Remote system's Idrac.

.PARAMETER Credential

    Specifies the credentials for Idrac connection.

.PARAMETER Session

    Specifies the session generated by New-RacSession for Idrac connection.

.PARAMETER User

    Specifies the username of the privileged local account to create in place of root.

.PARAMETER Password

    Specifies the current password of the privileged local account, usualy root.

.PARAMETER NewPassword

    Specifies the new password of the privileged local account whether you would like to change it.

.PARAMETER Hostname

    Specifies the full qualified domain name of the idrac interface.

.PARAMETER StaticIpAddress

    Specifies the static ip address of the idrac interface whether the current one has to be changed.

.PARAMETER PrefixLength

    Specifies the PrefixLength of the subnet mask of the idrac interface.

.PARAMETER NextHop

    Specifies the gateway of the idrac interface.

.PARAMETER PrimaryDns

    Specifies primary dns address of the idrac interface.

.PARAMETER SecondaryDns

    Specifies secondary dns address of the idrac interface.

.EXAMPLE

Set-RacTemplate -TemplatePath C:\temp\Idrac9_Template.xml -IpAddress 10.111.1.102 -Hostname idrac-panutaflax155.idrac.boursorama.fr

Note: le mot de passe sécurisé est indiqué en face avant du serveur (étiquette "IDRAC Default Password").

.EXAMPLE

Set-RacTemplate -TemplatePath C:\temp\Idrac9_Template.xml -IpAddress 10.111.1.102 -Hostname idrac-panutaflax155.idrac.boursorama.fr -User root -Password calvin -NewPassword NewSecurePassword:! -PrimaryDns 10.4.2.2 -SecondaryDns 10.4.1.2

.EXAMPLE

Set-RacTemplate -TemplatePath C:\temp\Idrac9_Template.xml -IpAddress 10.111.1.102 -Hostname idrac-panutaflax155.idrac.boursorama.fr -User root -Password calvin -NewPassword NewSecurePassword:! -StaticIpAddress 10.111.1.102 -PrefixLength 24 -NextHop 10.111.1.254 -PrimaryDns 10.4.2.2 -SecondaryDns 10.4.1.2

.NOTES

Date: 28/09/2023


#>

Function Set-RacTemplate {
    [CmdletBinding()]
    Param(
        [Parameter(mandatory=$true, HelpMessage="Path to template." )]
        [ValidateScript({
            if(-Not ($_ | Test-Path) ){
                throw "File or folder does not exist" 
            }
            if(-Not ($_ | Test-Path -PathType Leaf) ){
                throw "The Path argument must be a file. Folder paths are not allowed."
            }
                return $true
        })]
        [Alias("TP", "FilePath")]
        [string]$TemplatePath,

        [Parameter(mandatory=$true, HelpMessage="Current Ip Address.")]
        [Alias("Ip")]
        [string]$IpAddress,

        [Parameter(mandatory=$false, HelpMessage="Idrac power user, default is root")]
        [string]$User = 'root',

        [Parameter(mandatory=$false, HelpMessage="Default password for power user, usualy 'calvin'.")]
        [string]$Password = 'calvin',

        [Parameter(mandatory=$false, HelpMessage="New password, get it in Securden.")]
        [string]$NewPassword,

        [Parameter(Mandatory=$false, HelpMessage="Idrac fqdn wether it's not declared in DNS yet.")]
        [ValidatePattern("idrac-\w+\.idrac.boursorama.fr")]
        [string]$Hostname, 

        [Parameter(mandatory=$false, HelpMessage="Static Ip Address pushed with the template.")]
        [string]$StaticIpAddress,

        [Parameter(mandatory=$false, HelpMessage="Gateway pushed with the template.")]
        [Alias("GW")]
        [string]$NextHop,
        
        [Parameter(mandatory=$false, HelpMessage="Prefix Length aka bit mask format.")]
        [Alias("PL")]
        [string]$PrefixLength,
        
        [Parameter(mandatory=$false, HelpMessage="Primary DNS Address.")]
        [Alias("DNS1")]
        [string]$PrimaryDns,
        
        [Parameter(mandatory=$false, HelpMessage="Secondary DNS Address.")]
        [Alias("DNS2")]
        [string]$SecondaryDns
    )

    Filter ConvertTo-BinaryFromLength { ("1" * $_).PadRight(32, "0") }
    Filter ConvertTo-IPFromBinary { ([System.Net.IPAddress]"$([System.Convert]::ToInt64($_,2))").IPAddressToString }


    If ($null -eq $Hostname) { 
        Try {
            $Hostname = [System.Net.Dns]::GetHostEntry($IpAddress).HostName
        } Catch {
            Throw "$IpAddress cannot be resolved, please use -IpAddress parameter."
        }
    }
    
     If (-not [string]::IsNullOrEmpty($Hostname)) {

        Try {
            $HostEntry = [System.Net.Dns]::GetHostEntry($Hostname)
            If ($PSBoundParameters.Keys -eq 'StaticIpAddress') {
                If ($StaticIpAddress -ne $HostEntry.AddressList.IPAddressToString) {
                    Write-Warning "StaticIpAddress does not match $Hostname resolution"
                }
            } Else {
                $StaticIpAddress = $HostEntry.AddressList.IPAddressToString
                Write-Host "StaticIpAddress is not specified, I assume it's $StaticIpAddress" -ForegroundColor Yellow
            }
        } Catch {
            Throw "$Hostname cannot be resolved, please use -Hostname parameter."
        }
    } 
     
    Write-Host "Starting correction of the template $([System.Io.Path]::GetFileName($TemplatePath)): " -NoNewline
    Try {
        $ManualDNSEntry = "$IP,$Hostname"

        $xml = [xml](Get-Content -Path $TemplatePath)
        $xmlUserName = $xml.SelectSingleNode("//Attribute[@Name='Users.2#UserName']")
        If ($PSBoundParameters.Keys -eq 'NewPassword') { $xmlUserName.InnerText = $User }
        Else { [void]$xmlUserName.ParentNode.RemoveChild($xmlUserName)}

        $xmlPassWord = $xml.SelectSingleNode("//Attribute[@Name='Users.2#Password']")
        If ($PSBoundParameters.Keys -eq 'NewPassword') { $xmlPassWord.InnerText = $NewPassword }
        Else { [void]$xmlPassWord.ParentNode.RemoveChild($xmlPassWord)}


        $xmlManualDNSEntry = $xml.SelectSingleNode("//Attribute[@Name='WebServer.1#ManualDNSEntry']")
        $xmlManualDNSEntry.InnerText = $ManualDNSEntry

        $xmlRacName = $xml.SelectSingleNode("//Attribute[@Name='ActiveDirectory.1#RacName']")
        $xmlRacName.InnerText = $Hostname.Split('.')[0]

        $xmlRacName = $xml.SelectSingleNode("//Attribute[@Name='NIC.1#DNSRacName']")
        $xmlRacName.InnerText = $Hostname.Split('.')[0]

        $xmlAddress = $xml.SelectSingleNode("//Attribute[@Name='IPv4Static.1#Address']")
        $xmlNetMask = $xml.SelectSingleNode("//Attribute[@Name='IPv4Static.1#Netmask']")
        $xmlGateway = $xml.SelectSingleNode("//Attribute[@Name='IPv4Static.1#Gateway']")
        $xmlDNS1 = $xml.SelectSingleNode("//Attribute[@Name='IPv4Static.1#DNS1']")
        $xmlDNS2 = $xml.SelectSingleNode("//Attribute[@Name='IPv4Static.1#DNS2']")

        If ($PSBoundParameters.Keys -eq 'StaticIpAddress') { $xmlAddress.InnerText = $StaticIpAddress }
        Else { [void]$xmlAddress.ParentNode.RemoveChild($xmlAddress)}

        $Gateway = $PrefixLength | ConvertTo-BinaryFromLength | ConvertTo-IPFromBinary

        If ($PSBoundParameters.Keys -eq 'StaticIpAddress') { $xmlNetMask.InnerText = $Gateway }
        Else { [void]$xmlNetMask.ParentNode.RemoveChild($xmlNetMask)}

        If ($PSBoundParameters.Keys -eq 'StaticIpAddress') { $xmlGateway.InnerText = $NextHop }
        Else { [void]$xmlGateway.ParentNode.RemoveChild($xmlGateway)}

        If ($PSBoundParameters.Keys -eq 'StaticIpAddress') { $xmlDNS1.InnerText = $PrimaryDns }
        Else { [void]$xmlDNS1.ParentNode.RemoveChild($xmlDNS1)}

        If ($PSBoundParameters.Keys -eq 'StaticIpAddress') { $xmlDNS2.InnerText = $SecondaryDns }
        Else { [void]$xmlDNS2.ParentNode.RemoveChild($xmlDNS2)}


        # Boom !
        $TargetPath = [System.Io.Path]::Combine([System.Io.Path]::GetDirectoryName($TemplatePath),[System.Io.Path]::GetFileNameWithoutExtension($TemplatePath) + "_$($Hostname.Split('.')[0])" + [System.Io.Path]::GetExtension($TemplatePath))
        $xml.Save($TargetPath)

        Write-Host "OK" -ForegroundColor Green

        Write-Host "To import the template, please use the command:"
        Write-Host "`tImport-RacTemplate -TemplatePath $TargetPath -Ip_Idrac $IpAddress -Credential `$Credential -Target ALL -ShutdownType Graceful" -ForegroundColor Cyan


    } Catch {
        Write-Host "NOK" -ForegroundColor Red
        Throw $_
    }

}

Export-ModuleMember Set-RacTemplate -Alias set-idrac

